/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as HomeImport } from './routes/home'
import { Route as CategoriesImport } from './routes/categories'
import { Route as CalendarImport } from './routes/calendar'
import { Route as UserIdImport } from './routes/user.$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesRoute = CategoriesImport.update({
  path: '/categories',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarImport.update({
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const UserIdRoute = UserIdImport.update({
  path: '/user/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calendar': {
      preLoaderRoute: typeof CalendarImport
      parentRoute: typeof rootRoute
    }
    '/categories': {
      preLoaderRoute: typeof CategoriesImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/user/$id': {
      preLoaderRoute: typeof UserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  CalendarRoute,
  CategoriesRoute,
  HomeRoute,
  SigninRoute,
  SignupRoute,
  UserIdRoute,
])

/* prettier-ignore-end */
