/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedHomeImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCategoriesImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCalendarImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedUserIdImport } from './routes/_authenticated/user.$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeRoute = AuthenticatedHomeImport.update({
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCategoriesRoute = AuthenticatedCategoriesImport.update({
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCalendarRoute = AuthenticatedCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUserIdRoute = AuthenticatedUserIdImport.update({
  path: '/user/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/calendar': {
      preLoaderRoute: typeof AuthenticatedCalendarImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/categories': {
      preLoaderRoute: typeof AuthenticatedCategoriesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/home': {
      preLoaderRoute: typeof AuthenticatedHomeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/user/$id': {
      preLoaderRoute: typeof AuthenticatedUserIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedCalendarRoute,
    AuthenticatedCategoriesRoute,
    AuthenticatedHomeRoute,
    AuthenticatedUserIdRoute,
  ]),
  SigninRoute,
  SignupRoute,
])

/* prettier-ignore-end */
